### ISSUE TITLE
Turning off Wifi and turning on Wifi on Android doesn't work

### ISSUE THREAD

**Issue by vishalbhoj** [96boards/bugs#103]
Multiple turn off and turn on wifi fails. Gives timeout:
[  202.531395] cfg80211: Calling CRDA to update world regulatory domain
[  202.705340] wlcore: down
[  206.094323] mmc_host mmc2: Bus speed (slot 0) = 25000000Hz (slot req 400000Hz, actual 390625HZ div = 32)
[  206.128805] mmc_host mmc2: Bus speed (slot 0) = 25000000Hz (slot req 25000000Hz, actual 25000000HZ div = 0)
[  207.887565] wlcore: ERROR timeout waiting for the hardware to complete initialization
[  207.943992] mmc_host mmc2: Bus speed (slot 0) = 25000000Hz (slot req 400000Hz, actual 390625HZ div = 32)
[  207.980012] mmc_host mmc2: Bus speed (slot 0) = 25000000Hz (slot req 25000000Hz, actual 25000000HZ div = 0)

**Comment by docularxu** [comment]
This is supposed to be fixed by https://github.com/96boards/linux/pull/77
Waiting for Vishal to test and feedback.

**Comment by vishalbhoj** [comment]
The patch works for Android as well.

**Comment by docularxu** [comment]
Verified on Android snapshot build 119. Pass.
