### ISSUE TITLE
usb ethernet adapter doesn't work on Android, no IP address assigned.

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#105]
Found this issue on builds.96boards.org/snapshots/hikey/aosp/105
usb ethernet adapter doesn't work on Android, no IP address assigned, no DNS. Here is the logcat log;

[  398.131194] usb 1-1.1: new full-speed USB device number 10 using dwc2
[  398.254153] usb 1-1.1: not running at top speed; connect to a high speed hub
[  398.275335] usb 1-1.1: New USB device found, idVendor=0b95, idProduct=772b
[  398.282235] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  398.289552] usb 1-1.1: Product: AX88772C
[  398.293490] usb 1-1.1: Manufacturer: ASIX Elec. Corp.
[  398.298548] usb 1-1.1: SerialNumber: 000016
[  399.156052] asix 1-1.1:1.0 eth0: register 'asix' at usb-f72c0000.usb-1.1, ASIX AX88772B USB 2.0 Ethernet, 00:0e:c6:fa:bf:fd
D/EthernetNetworkFactory( 1706): Started tracking interface eth0
D/CommandListener( 1297): Setting iface cfg
D/CommandListener( 1297): Trying to bring up eth0
[  399.998675] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
E/NetdConnector( 1706): NDC Command {20 interface setcfg eth0 0.0.0.0 0 up multicast broadcast} took too long (848ms)
D/EthernetNetworkFactory( 1706): updateInterface: eth0 link down
D/EthernetNetworkFactory( 1706): updateInterface: eth0 link down
D/EthernetNetworkFactory( 1706): updateInterface: eth0 link down
[  401.807347] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
D/EthernetNetworkFactory( 1706): update[  401.819291] asix 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
Interface: eth0 [  401.819831] init: no such service 'dhcpcd_eth0:-f /system/etc/dhcpcd/dhcpcd.conf -h android-75a15a19aeceda87 eth0'
link up
I/EthernetNetworkFactory( 1706): dhcpThread(+eth0): mNetworkInfo=[type: Ethernet[], state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: 00:0e:c6:fa:bf:fd, roaming: false, f]
D/NetUtils( 1706): dhcp_do_request failed : eth0 (new)
E/EthernetNetworkFactory( 1706): DHCP request error:Timed out waiting for dhcpcd to start

W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client
E/browser ( 2616): Console: Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png data:text/html,chromewebdata:12
W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client
E/browser ( 2616): Console: Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png data:text/html,chromewebdata:12
W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client
V/WindowManager( 1706): Adding window Window{29c371aa u0 PopupWindow:33d54898} at 5 of 10 (after Window{15e09ede u0 com.android.browser/com.android.browser.BrowserActivity})
V/WindowManager( 1706): Adding window Window{7befe76 u0 PopupWindow:17b17755} at 5 of 10 (after Window{15e09ede u0 com.android.browser/com.android.browser.BrowserActivity})
V/WindowManager( 1706): Adding window Window{18f170e4 u0 PopupWindow:9a9e56a} at 6 of 11 (after Window{7befe76 u0 PopupWindow:17b17755})
W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client
W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client
I/art     ( 1706): Explicit concurrent mark sweep GC freed 15161(781KB) AllocSpace objects, 1(64KB) LOS objects, 33% free, 7MB/10MB, paused 1.670ms total 78.840ms
W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client
W/AudioTrack( 1706): AUDIO_OUTPUT_FLAG_FAST denied by client

**Comment by vishalbhoj** [comment]
https://github.com/96boards/android_device_linaro_hikey/commit/d99d1751fb229ac2ee6813121d7e00ff7049f496  should fix the issue.

**Comment by vishalbhoj** [comment]
Ethernet should now work on http://builds.96boards.org/snapshots/hikey/aosp/107?dl=/snapshots/hikey/aosp/107/  provided the driver for the usb dongle is built in the kernel. Worked with Guodong's usb ethernet dongle.

**Comment by sbambrough** [comment]
This worked for me in snapshot 110.
