### ISSUE TITLE
1.8V supply not enabled on HiKey LS expansion bus

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#106]
The 1.8V supply must be enabled on the HiKey LS expansion bus for all OSes. 
Without it the Maker Mezzanine module will not operate (to be precise none of the level shifted signals will be available on the 0.1" maker header)

**Comment by hzhuang1** [comment]
Do you mean LDO5 on I2C buses? But LDO5 is always enabled. Otherwise, we can't detect GPIO3_0 in hisilicon fastboot bootloader.

**Comment by gcgrey** [comment]
LDO21_1V8 - LS Expansion bus pin 35

**Comment by hzhuang1** [comment]
Is it ok to enable it in kernel? I think that nobody want to use it in bootloader stage. Is it right?

**Comment by gcgrey** [comment]
Good question. I'll defer to Scott but I can think of some use cases. 
For now I am OK with the kernel. 
In future we should probably enable the boot loader as well/instead because if someone designs a mezzanine/module using this rail that is needed at boot time (e.g. touch screen display, storage or networking interface) then the rail will be needed.

**Comment by sbambrough** [comment]
I agree with George, there will come a time when a mezzanine module is needed at boot time.  For now the kernel should be ok.

**Comment by docularxu** [comment]
For kernel enablement, need to add a ldo21 node into arch/arm64/boot/dts/hi6220.dtsi, together with 'regulator-always-on' property.

PS: George:  would say they can be fixed in next months release (and snapshots in the interim)

**Comment by hzhuang1** [comment]
Pull request is submitted in https://github.com/96boards/linux/pull/76

**Comment by docularxu** [comment]
Measured 1.8V on Pin 35 of J2, using Android snapshot build 119. 
Pass.
