### ISSUE TITLE
HiKey expansion bus UART port missing

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#107]
Expansion bus UART0 appears in Debian as /dev/ttyAMA2 
Expansion bus UART1 does not appear

ttyAMA0 corresponds to the debug port (not populated in production) which is fine. 
ttyAMA1 appears but its function is unknown?

Please explain the purpose of ttyAMA1 and enable Expansion bus UART1 as /dev/ttyAMA3

**Comment by docularxu** [comment]
ttyAMA0 is the debug port.
ttyAMA1 is used by Bluetooth as uart.
ttyAMA2 and ttyAMA3 corresponds to Expansion bus UART0 and UART1 respectively.
ttyAMA2 has been enabled for a while for verification purpose.

So, now I will submit a patch to enable ttyAMA3.

**Comment by docularxu** [comment]
So, George, could you please confirm one thing: did you verified the functionality of ttyAMA2 (Expansion bus UART0 appears in Debian as /dev/ttyAMA2), how it works?

**Comment by gcgrey** [comment]
ttyAMA2 seems to work fine - defaults to 9600 baud - tested using MacOS X terminal interface at 9600 and 115200 baud in Debian build.

**Comment by Leo-Yan** [comment]
For Enable UART3/4: https://github.com/96boards/linux/pull/75

**Comment by docularxu** [comment]
This has been enabled since Android snapshot build 119, Debian build 305.
George, please verify when you get a chance. Thanks.

**Comment by gcgrey** [comment]
Verified as fixed in current Debian snapshots - closing
