### ISSUE TITLE
Mali EULA click thru not working properly.

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#109]
Tried on Debian snapshot 303: http://builds.96boards.org/snapshots/hikey/debian/303.
Tried on AOSP snapshot 110: http://builds.96boards.org/snapshots/hikey/aosp/110

Click on file that has EULA associated with it.
EULA appears.
Agree to EULA.
Should get a dialog allowing me to download the file to my local machine.
Doesn't happen.
Click on same file again --- No EULA appears, but expected dialog does show up.

**Comment by doanac** [comment]
The same type of build-info file works fine on snapshots.l.o. I think this must have something to do with the js/css theming added for 96boards. I'll take a look at this.

**Comment by doanac** [comment]
deployed this fix into production:
  https://git.linaro.org/infrastructure/ansible-playbooks.git/commit/a6d09b47c350aafb720b372d0d500f038ecd0f83

**Comment by sbambrough** [comment]
Works for me and others on todays call. Closing.
