### ISSUE TITLE
Bluetooth LED does not light on Bluetooth activity

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#112]
On Snapshots AOSP 112 build, Bluetooth does not light up when we play Audio via a Bluetooth speaker

**Comment by docularxu** [comment]
Need to add led trigger into tty_hci driver.

**Comment by docularxu** [comment]
Today I implemented that for Android and verified locally.

To keep both Debian and Android happy, one thing we need to do in Android is: run this command after modules are inserted:
 # echo hci1rx > /sys/devices/leds/leds/bt_active/trigger

I will ping Vishal to see what suggestion he has.

**Comment by docularxu** [comment]
Commit submitted. https://github.com/96boards/linux/pull/78

And Vishal confirmed that the above 'echo' command has been added into Android booting script.

**Comment by docularxu** [comment]
Verified using Bluetooth mouse and Soundbox. It survives during (and after) multiple times of turning on/off of Bluetooth.

Pass.
