### ISSUE TITLE
New file images.tar.xz

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#114]
Looking at snapshot 112.

I don't think you understood when Guodong asked for files to be compressed to reduce download time.
We don't want to have a single archive with all images.

What we want is individual files compressed with zip.  ie:
boot_fat.img.gz
cache.img.gz
system.img.gz
userdata.img.gz

These files must be unarchived easily in Windows.

**Comment by fboudra** [comment]
you meant foo.bar.zip right? 7-zip is freely available to extract xz files.

**Comment by sbambrough** [comment]
Don't really care how they are compressed.  Just that it should be possible to uncompress them on Windows and Mac easily.  Best possible user scenario is the user would not have to download and install any software; just use that which comes with OS.  Barring that we  should document what software is needed and provide links to downloads.

**Comment by vishalbhoj** [comment]
https://review.linaro.org/#/c/6006/ should address the issue.

**Comment by vishalbhoj** [comment]
fixed in http://builds.96boards.org/snapshots/hikey/aosp/117 .
