### ISSUE TITLE
UEFI fails to boot Debian

### ISSUE THREAD

**Issue by hzhuang1** [96boards/bugs#122]
If we use the partition table for UEFI, we'll fail to boot debian system. If we use the partition table for hisilicon bootloader, we could boot debian system successfully.

After investigated this issue, it's caused that system partition is limited in 1.5GB in partition table of UEFI. But debian needs the system space larger than 3.0GB. A draft patch is delivered to Fathi, and he'll distinguish different system partition size for both debian and android system in build script.

**Comment by fboudra** [comment]
Build system has been updated to generate ptable-aosp.img and ptable-linux.img:
https://git.linaro.org/ci/job/configs.git/blob/HEAD:/96boards-hikey-uefi.yaml

Haojian patch has also been commited and we now use l-loader master branch:
https://github.com/96boards/l-loader/commit/51b065b1d355e1ace800d1cb056ac7cd427384b5

The wiki has been updated to reflect these changes:
https://github.com/96boards/documentation/wiki/UEFI/_compare/e7376f897adb7b2872b778fb7703d6c8c4ffab69...2d1b2c85ce3f15505291ce9ea3337c3d2c711f55
