### ISSUE TITLE
Regression on HDMI on Snapshot 125

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#14]
I'm seeing a regression on Snapshot 125 with HDMI port. 
Previous Snapshot 118 runs fine from eMMC

Using Release files + Snapshot boot-fat.emmc.img and jessie....emmc.img

Snapshot 125 flashes LEDs but no output seen on HDMI port. 
Revert to Snapshot 118 and HDMI comes up

**Comment by ldts** [comment]
HDMI fixes from the LT were pulled yesterday. they probably went into release 125. LT to review.

**Comment by ldts** [comment]
fix under test:  https://github.com/96boards/linux/pull/12

**Comment by gcgrey** [comment]
Fixed in recent builds.
