### ISSUE TITLE
HDMI Display wrap issue

### ISSUE THREAD

**Issue by fboudra** [96boards/bugs#2]
_From @usmanahmad-linaro on February 17, 2015 7:58_

The display on the board wraps around several lines, although the overall image is correct.

_Copied from original issue: 96boards/linux#2_

**Comment by sbambrough** [comment]
This was only a problem with Android.  A fix has been provided by HiSilicon.  Awaiting confirmation that this is fixed in the current builds.

**Comment by ldts** [comment]
@sbambrough: do you know if there was a commit associated to this fix? there were a number of commits merged to address  HDMI issues but AFAIR no direct indication of which fixed what.

**Comment by sbambrough** [comment]
Off hand no.  It was mixed in with the HDMI driver fixes IIRC.  We grabbed
them out of private git.

Scott

On Mon, Mar 16, 2015 at 4:03 PM, Jorge A. Ramirez-Ortiz <
notifications@github.com> wrote:

> @sbambrough <https://github.com/sbambrough>: do you know if there was a
> commit associated to this fix? there were a number of commits merged to
> address HDMI issues but AFAIR no direct indication of which fixed what.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/2#issuecomment-81906696>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>

**Comment by docularxu** [comment]
I tested with Android - https://builds.96boards.org/snapshots/hikey/android/38 on my home TV. I didn't see this issue.

The fix is:
f7754a0 gpu/drm: hisilicon: fix display wrap issue and set 720p as default mode     Xinliang Liu (Wed Mar 4 11:32:06 2015)
And hase been merged into hikey branch.

**Comment by sbambrough** [comment]
I filed a bug similar to this with ALIP snapshot 251 (https://github.com/96boards/bugs/issues/37).
Display still wraps.

Scott

**Comment by usmanahmad-linaro** [comment]
Closing as the similar bug logged in https://github.com/96boards/bugs/issues/37 has been resolved.
