### ISSUE TITLE
HiKey: ARM TF: ATF boot hangs sometimes

### ISSUE THREAD

**Issue by suihkulokki** [96boards/bugs#20]
ATF boot sometimes gets stuck, often between loading BL1 and BL2. With second try boot usually passes.

Koen also reported this on mailing list: >I do have the problem where I have to power cycle twice to start UEFI from time to time.

Typical stuck boot from my side:
```
-snip-
NOTICE:  BL1: Built : 15:25:44, Mar  9 2015
NOTICE:  succeed to init lpddr3 rank0 dram phy
INFO:    lpddr3_freq_init, set ddrc 533mhz
INFO:    init ddr3 rank0 in 533MHz
INFO:    ddr3 rank1 init pass in 533MHz
INFO:    Elpida DDR
NOTICE:  BL1: Booting BL2
-snip
```

**Comment by koenkooi** [comment]
Same exact issue here.

**Comment by Leo-Yan** [comment]
Could u help try these pull request: https://github.com/96boards/arm-trusted-firmware/pull/1, at my side i find after applied the patches the booting can be much more stable.

**Comment by suihkulokki** [comment]
Build with fixes:

https://builds.96boards.org/snapshots/hikey/uefi/8

I've tried booting ~10 times and haven't observed the mentioned hang between bl1-bl2 anymore.

**Comment by Leo-Yan** [comment]
Thanks for trying.
So do u think we can say this issue has been fixed with these patches?

Thanks,
Leo Yan

**Comment by suihkulokki** [comment]
Lets close this now
