### ISSUE TITLE
udhcpc does't work properly

### ISSUE THREAD

**Issue by rengolin** [96boards/bugs#21]
I can't directly from the command line, which probably means it's not symlinked correctly to busybox binary.

When I do run "sudo busybox udhcpc -i eth0" and get an IP, the IP doesn't stick to the interface. No route, no IP on "ifconfig eth0", etc.

I'm using a dongle that works on any other ARM/AArch64 board.

**Comment by rengolin** [comment]
dhclient is available (though only visible by root), and adding /etc/network/interfaces.d/eth0 with dhcp does work.

I'm not getting the resolve.conf done, though.

**Comment by fboudra** [comment]
your issues have been fixed a long time ago on the snapshots builds. I suspect you still use the released image at HKG15?

**Comment by rengolin** [comment]
I'm following the Getting Started guide. If that doesn't work, it needs updating...

**Comment by fboudra** [comment]
it doesn't need updating, it's documented in the known issues. Debian doesn't use udhcpc but ISC dhcp.

**Comment by rengolin** [comment]
Could it at least have a hint on the "setting up network section"? Something like "look at the known issues"?

**Comment by rengolin** [comment]
Done.

**Comment by fboudra** [comment]
thanks
