### ISSUE TITLE
ARM TF: DDR works only at 533MHz

### ISSUE THREAD

**Issue by ldts** [96boards/bugs#23]

**Comment by hzhuang1** [comment]
Currently ddr800mhz patch could work on 7 boards, and only failed to run on one board. Now submit the ddr800mhz patch to fathi.

**Comment by usmanahmad-linaro** [comment]
from Koen: I've created a pull request for it:
https://github.com/96boards/arm-trusted-firmware/pull/2

**Comment by hzhuang1** [comment]
Fixed in https://github.com/96boards/arm-trusted-firmware/pull/34
