### ISSUE TITLE
HiKey: Kernel: DW USB is slow and produces lots of errors

### ISSUE THREAD

**Issue by suihkulokki** [96boards/bugs#26]
Using the 3.18 kernel from github, the boot looks failrly ok:

[    3.199467] f72c0000.usb supply vusb_d not found, using dummy regulator
[    3.206131] f72c0000.usb supply vusb_a not found, using dummy regulator
[    3.244855] dwc2 f72c0000.usb: EPs: 16, dedicated fifos, 1920 entries in SPRAM
[    4.105345] dwc2 f72c0000.usb: DWC OTG Controller
[    4.110065] dwc2 f72c0000.usb: new USB bus registered, assigned bus number 1
[    4.117146] dwc2 f72c0000.usb: irq 109, io mem 0x00000000
[    4.123142] hub 1-0:1.0: USB hub found
[    4.126916] hub 1-0:1.0: 1 port detected
[    4.131098] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.137635] ehci-pci: EHCI PCI platform driver
[    4.142145] ehci-platform: EHCI generic platform driver

[    4.544859] usb 1-1: new full-speed USB device number 2 using dwc2
[    4.679396] fixed_5v_hub: 5000 mV 
[    4.755066] usb 1-1: not running at top speed; connect to a high speed hub
[    4.755700] hub 1-1:1.0: USB hub found
[    4.755791] hub 1-1:1.0: 3 ports detected

[    5.035080] usb 1-1.1: new full-speed USB device number 3 using dwc2
[    5.188068] usb 1-1.1: not running at top speed; connect to a high speed hub
[    5.279580] asix 1-1.1:1.0 eth0: register 'asix' at usb-f72c0000.usb-1.1, DLink DUB-E100 USB Ethernet, 00:80:c8:37:2b:fd
[    6.141093] asix 1-1.1:1.0 eth0: link down
[    7.202111] asix 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC5E1

But after a while, the usb errors start coming:

[  781.987226] usb usb1: clear tt 1 (9033) error -22
[  782.000570] dwc2 f72c0000.usb: dwc2_hc_chhltd_intr_dma: Channel 4 - ChHltd set, but reason is unknown
[  782.009801] dwc2 f72c0000.usb: hcint 0x00000002, intsts 0x06000029

[  911.397471] usb usb1: clear tt 1 (9033) error -22
[  911.410677] dwc2 f72c0000.usb: dwc2_hc_chhltd_intr_dma: Channel 7 - ChHltd set, but reason is unknown
[  911.419908] dwc2 f72c0000.usb: hcint 0x00000002, intsts 0x06000029
[  911.525509] usb usb1: clear tt 1 (1032) error -22

All the time, USB speed gets slower and slower. Typical download speed over asix ethernet is 80KB.

**Comment by fboudra** [comment]
I can confirm same behavior. usb usb1: clear tt 1 (9033) error -22 message is recent. I haven't seen it before (at least not with the released image).

**Comment by gaozhangfei** [comment]
Test with android, not find issue.

branch: origin/hikey
git log --oneline 
7ef6764 Merge pull request #24 from ldts/hikey
23f1458 dts/hi6220: enable bluetooth at 3mbps
a378686 Merge pull request #21 from ldts/hikey
b0da832 drivers/clk: hi6220: initialize UART1 clock to 150MHz

scripts/kconfig/merge_config.sh android/configs/android-base.cfg arch/arm64/configs/defconfig

make -j4; mkbootimg  --kernel arch/arm64/boot/Image --ramdisk /home/zhangfei/Downloads/ramdisk.img --cmdline "k3v2mem hisi_dma_print=0 vmalloc=484M no_irq_affinity loglevel=7 androidboot.hardware=hikey selinux=0" --base 0x07400000 --tags-addr 0x09e00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000  --output boot.img

cp arch/arm64/boot/dts/hi6220-hikey.dtb tmp/; dtbTool -o dt.img -s 2048 -p scripts/dtc/ tmp/

log:
https://pastebin.linaro.org/view/f65fb03a

Test adb & u disk.

By the way, usb code has not been modified for long time.

**Comment by suihkulokki** [comment]
It would then seem either the error doesn't manifest on mass storage devices, or the difference is caused by me using UEFI.

**Comment by koenkooi** [comment]
is USB still limited to 12Mbit/s on the 3.18 vendor branch?

**Comment by gaozhangfei** [comment]
we can change speed via debugfs, suppose it is in 

2. If user want to switch speed.
    mount -t debugfs none /mnt
    cd /mnt/f72c0000.usb/
    cat config
    echo 1 > config /* switch to full speed */
    echo 0 > config /* switch to high speed */
    
    Then unplug usb, host mode will switch to full speed, all ports don't support high speed in host mode.
    Every time switch speed, just need plug usb -> unplug usb from OTG.
    
    For example:
    mount -t debugfs none /mnt
    cd /mnt/f72c0000.usb/
    cat config
     input para should be:
     0, HIGH speed;
     1, FULL speed
     Current speed=0: HIGH speed
    
    If unplug usb and insert mouse now, it will fail.
     usb 1-1-port1: unable to enumerate USB device
    
    echo 1 > config
     Current speed=1: FULL speed
    cat config
     input para should be:
      0, HIGH speed;
      1, FULL speed
     Current speed=1: FULL speed
    
    If unplug usb from OTG and insert mouse now
     usb 1-1.1: new low-speed USB device number 8 using dwc2

**Comment by usmanahmad-linaro** [comment]
Closing as duplicate https://github.com/96boards/bugs/issues/35.
