### ISSUE TITLE
HiKey. ARM TF: Implement MCU firmware loading in ARM TF.

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#28]
MCU firmware loading needs to be implemented in ARM TF.

**Comment by sbambrough** [comment]
Now i'm trying to enabling mcu/acpu with ATF, below are current status and issues:

1. In ATF, loading mcu binaries has been finished, and i use the 
register AO_SC_MCU_SUBSYS_STAT2 to check mcu's PC value, it can confirm mcu has released successfully. The image's loading sections' info as below: 

hisi_mcu_load_image: section index 0
hisi_mcu_load_image: secs mcu addr f6000000 des_offset 0 src_offset 1000200 size 512
hisi_mcu_load_image: section index 1
hisi_mcu_load_image: secs mcu addr f6000200 des_offset 200 src_offset 1000400 size 27828
hisi_mcu_load_image: section index 2
hisi_mcu_load_image: secs mcu addr f6007200 des_offset 7200 src_offset 10070b4 size 1024
hisi_mcu_load_image: section index 3
hisi_mcu_load_image: secs mcu addr fff8e000 des_offset fff8e000 src_offset 10074b4 size 12704
hisi_mcu_load_image: section index 4
hisi_mcu_load_image: secs mcu addr 5e00000 des_offset c000 src_offset 100a654 size 82912
hisi_mcu_load_image: section index 5
hisi_mcu_load_image: secs mcu addr 5e143e0 des_offset 203e0 src_offset 101ea34 size 12816
hisi_mcu_load_image: section index 6
hisi_mcu_load_image: secs mcu addr 5e1c1d0 des_offset 281d0 src_offset 1021c44 size 3060
hisi_mcu_load_image: section index 7
hisi_mcu_load_image: secs mcu addr 5e1cdc4 des_offset 28dc4 src_offset 1022838 size 2616

2. But after run into kernel, when attempting to trigger cpu frequency change, it does not work. Below is a dump of the mcu related registers:

PERI_SC_RESERVED8_ADDR = 0x02000020
AO_SC_PERIPH_RSTDIS4   = 0
AO_SC_PERIPH_RSTSTAT4  = 0
AO_SC_PERIPH_CLKEN4    = 0
AO_SC_PERIPH_CLKSTAT4  = 0x39018f09
AO_SC_MCU_SUBSYS_CTRL1 = 0x05e00000
AO_SC_SYS_CTRL2        = 0

**Comment by sbambrough** [comment]
Leo found he has written the wrong register for ddr remap, after this is modified as indicated below, every time the SoC will be reset automatically; so mcu seems to have begun to work, but there must be some condition that has been triggered for reset.

/* set mcu ddr remap configuration */
-       mmio_write_32(AO_SC_MCU_SUBSYS_CTRL1, MCU_SYS_MEM_ADDR);
+       mmio_write_32(AO_SC_MCU_SUBSYS_CTRL2, MCU_SYS_MEM_ADDR);

**Comment by Leo-Yan** [comment]
We need initialize the ACPU parameters in ATF, otherwise MCU will check the parameters are wrong and trigger reset. Now is debugging on this.

**Comment by Leo-Yan** [comment]
Now mcu loading can work well at my side, and can change the cpu frequency successfully in kernel, i will take 1~2 more days to polish patches and send pull request.

**Comment by Leo-Yan** [comment]
Has finished related work in: https://github.com/96boards/arm-trusted-firmware/pull/6;
reviewing is ongoing.

**Comment by Leo-Yan** [comment]
https://github.com/96boards/arm-trusted-firmware/pull/20 Has been merged, we can close this issue.

**Comment by sbambrough** [comment]
Closing per previous comment
