### ISSUE TITLE
ATF+UEFI: Need reserve memory from address 0x0

### ISSUE THREAD

**Issue by Leo-Yan** [96boards/bugs#29]
In hisilicon old code base, it will reserve memory from address 0x0; and i saw there have some hard code for these memory regions for using MCU and thermal sensor.

Currently ATF+UEFI reserve the high memory region, this is a good solution compare to before. But it also will introduce the difficult w/t alignment old hisilicon code base.

So suggest still use the old way to reserve memory region, we can get one workable version.

**Comment by sbambrough** [comment]
What needs to be done for this?

**Comment by Leo-Yan** [comment]
On Fri, Apr 24, 2015 at 12:22:39PM -0700, Scott Bambrough wrote:
> What needs to be done for this?

MCU firmware will run in sram, it also have section in DDR, so this is
conflict w/t kernel's memory region. Now we use the W/A to reserve
this memory region in DTB so kernel will not allocate it.

So far have not seen other conflict.
