### ISSUE TITLE
HiKey. UEFI: USB support

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#31]
Implement USB driver in UEFI

**Comment by gaozhangfei** [comment]
In order to enable fastboot flash, 
1, usb driver for download to ddr, USB_DEVICE_PROTOCOL
2. flush from ddr to emmc/sd, FASTBOOT_PLATFORM_PROTOCOL

In check how to enable FASTBOOT_PLATFORM_PROTOCOL, for the whole testing sequence

http://tianocore.sourceforge.net/wiki/EmbeddedPkg/AndroidFastBoot

**Comment by gaozhangfei** [comment]
pull request
https://github.com/96boards/edk2/pull/3

**Comment by hzhuang1** [comment]
merged
