### ISSUE TITLE
ARM TF: BL30 and BL32 memory section may have conflict so introduce secondary cores hang

### ISSUE THREAD

**Issue by Leo-Yan** [96boards/bugs#39]
Now if enable BL32 for OPTEE, though the cpu0 can boot up, but usually the secondary cores cannot boot up successfully. So suspect BL30 and BL32 may have some memory section conflict.

**Comment by vchong** [comment]
BL32 is using 3f00_0000, and BL30 0100_0000, so it should be ok? If you don't insert bl32 into fip.bin, do the secondary cores still boot up?

**Comment by Leo-Yan** [comment]
hi Victor,
 
Below are some analysis for the secendary cores cannot boot up
successfully:
 
1. The failure is caused by ATF w/t TEEOP + UEFI w/t debug version, so
 the building steps are:

ATF:
make PLAT=hikey DEBUG=1 LOG_LEVEL=50 CRASH_REPORTING=1 BL33=$BL33
BL32=$BL32 PLAT_TSP_LOCATION=tdram SPD=opteed

UEFI:
../uefi-tools/uefi-build.sh -b DEBUG hikey

2. After enabled ATF, the hang is caused by below code:

> diff --git a/services/std_svc/psci/psci_afflvl_on.c b/services/std_svc/psci/psci_afflvl_on.c
> index 0ee03cb..b1811b2 100644
> --- a/services/std_svc/psci/psci_afflvl_on.c
> +++ b/services/std_svc/psci/psci_afflvl_on.c
> @@ -337,8 +337,8 @@ static void psci_afflvl0_on_finish(aff_map_node_t *cpu_node)
>        * Dispatcher to let it do any bookeeping. If the handler encounters an
>        * error, it's expected to assert within
>        */
> -     if (psci_spd_pm && psci_spd_pm->svc_on_finish)
> -             psci_spd_pm->svc_on_finish(0);
> +     //if (psci_spd_pm && psci_spd_pm->svc_on_finish)
> +     //      psci_spd_pm->svc_on_finish(0);
>  
>       /*
>        * Generic management: Now we just need to retrieve the

could u continue to check the code in tee.bin to see why the
svc_con_funinish call back function will introduce the hang issue?

**Comment by hzhuang1** [comment]
It's fixed already.
