### ISSUE TITLE
android hung at bluetooth

### ISSUE THREAD

**Issue by gaozhangfei** [96boards/bugs#43]
Test images of http://builds.96boards.org/snapshots/hikey/android/63 with fastboot.
Android can not boot up.

log
[   12.381465] ------------[ cut here ]------------
[   12.386447] WARNING: CPU: 1 PID: 1 at /home/buildslave/workspace/linaro-android_armv8-android-hikey-3.18/build/kernel/linaro/hisilicon/net/wireless/reg.c:511 regulatory_init+0x88/0x128 [cfg80211]()
[   12.404089] db.txt is empty, you should update it...
[   12.408900] Modules linked in: cfg80211(+) rfkill
[   12.413959] CPU: 1 PID: 1 Comm: init Not tainted 3.18.0+ #1
[   12.419552] Call trace:
[   12.422050] [<ffffffc0000885b8>] dump_backtrace+0x0/0x124
[   12.427540] [<ffffffc0000886ec>] show_stack+0x10/0x1c
[   12.432680] [<ffffffc000815b78>] dump_stack+0x74/0xb8
[   12.437770] [<ffffffc0000aff00>] warn_slowpath_common+0x90/0xb8
[   12.443768] [<ffffffc0000aff74>] warn_slowpath_fmt+0x4c/0x58
[   12.449679] [<ffffffbffc07c17c>] regulatory_init+0x84/0x128 [cfg80211]
[   12.456507] [<ffffffbffc07c070>] cfg80211_init+0x70/0xf8 [cfg80211]
[   12.462863] [<ffffffc000081554>] do_one_initcall+0x120/0x1ac
[   12.468564] [<ffffffc00011b3b4>] load_module+0x156c/0x1da0
[   12.474134] [<ffffffc00011bca4>] SyS_init_module+0xbc/0xf0
[   12.479644] ---[ end trace 78ad5c05f38f684e ]---
[   12.484457] cfg80211: Calling CRDA to update world regulatory domain
[   29.692907] random: nonblocking pool is initialized
[   29.767935] wl18xx_driver wl18xx.0.auto: Direct firmware load for ti-connectivity/wl1271-nvs.bin failed with error -2
[   29.778698] wl18xx_driver wl18xx.0.auto: Falling back to user helper
[   33.525272] Bluetooth: Core ver 2.19
[   33.529195] NET: Registered protocol family 31
[   33.533730] Bluetooth: HCI device and connection manager initialized
[   33.540204] Bluetooth: HCI socket layer initialized
[   33.545192] Bluetooth: L2CAP socket layer initialized
[   33.550381] Bluetooth: SCO socket layer initialized
[   33.995858] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[   34.001908] Bluetooth: HIDP socket layer initialized
[   34.745154] Bluetooth: RFCOMM TTY layer initialized

hung

**Comment by vishalbhoj** [comment]
5/5 times Android did not hang after the above msg for me with build #63 , however I have seen similar issue when kernel is changed from an image without updating the kernel modules in system partition.

**Comment by docularxu** [comment]
I tested this with build #64. Here is the images I am using:
a) fastboot and all binaries: https://builds.96boards.org/snapshots/hikey/binaries/20150408
b) android snapshot builds: https://builds.96boards.org/snapshots/hikey/android/64 
 NOTE: I AM USING boot-fat.img, 
and cache.img  system.img  userdata.img

Test result: I cannot  reproduce this issue. I can see Android logo then UI desktop on my HDMI monitor. And it doesn't hang.

**Comment by docularxu** [comment]
Assigning this back to Zhangfei. Please provide more details on which images you are using and what's the result. I suggest you test with only the images in official website: builds.96boards.org. 

Can you try the images I mentioned above and see what happens?

If not reproducible, please close this.

**Comment by gaozhangfei** [comment]
a) fastboot and all binaries: https://builds.96boards.org/snapshots/hikey/binaries/20150408
b) android snapshot builds: https://builds.96boards.org/snapshots/hikey/android/64 
try this, bluetooth can pass
