### ISSUE TITLE
uefi fastboot downloading huge files too slow

### ISSUE THREAD

**Issue by gaozhangfei** [96boards/bugs#44]
When using uefi downloading huge files (1G)
In the second time. it is too slow.

host:
 fastboot flash system  hikey-jessie_developer_20150407-253.emmc.img
target reported max download size of 536870912 bytes
sending sparse 'system' (523664 KB)...
OKAY [164.336s]
writing 'system'...
OKAY [ 45.326s]
sending sparse 'system' (434122 KB)...

target:
[1] Linux from eMMC
        - VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(6,GPT,5C0F213C-17E1-4149-88C8-8B50FB4EC70E,0x7000,0x20000)/Image
        - Arguments: dtb=hi6220-hikey.dtb console=ttyAMA0,115200 earlycon=pl011,0xf8015000 root=/dev/mmcblk0p9 ro rootwait
[2] f
        - VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(6,GPT,5C0F213C-17E1-4149-88C8-8B50FB4EC70E,0x7000,0x20000)/fastboot.efi
        - Arguments: 
[3] Shell
[4] Boot Manager
Start: 2
add-symbol-file /home/zhangfei/work/96board/linaro-edk2/Build/HiKey/DEBUG_GCC48/AARCH64/EmbeddedPkg/Application/AndroidFastboot/AndroidFastbootApp/
DEBUG/AndroidFastbootApp.dll 0x3AA41260
Loading driver at 0x0003AA41000 EntryPoint=0x0003AA41260 AndroidFastbootApp.efi
Android Fastboot mode - version 0.4. Press any key to quit.
Downloading 536232132 bytes
536232132 / 536232132 bytes downloaded (100%)
Flashing partition system
Done.
Downloading 444541388 bytes
278529034 / 444541388 bytes downloaded (62%)

**Comment by hzhuang1** [comment]
If we wait for a long time, the huge image (android or debian rootfs) could be flushed into eMMC. But UEFI couldn't boot the rootfs. It seems that the rootfs is broken.

If we use fastboot bootloader to flush the rootfs, UEFI could boot rootfs successfully.

**Comment by gaozhangfei** [comment]
https://github.com/96boards/edk2/pull/9

**Comment by hzhuang1** [comment]
The pull request #9 fixed downloading huge image slowly issue. But if flush rootfs, we still met issue on mounting. Create a new one for flushing rootfs issue.
