### ISSUE TITLE
Android snapshot build #64, fails to show Android desktop

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#45]
With these images:
a) fastboot and all binaries: https://builds.96boards.org/snapshots/hikey/binaries/20150408
b) android snapshot builds: https://builds.96boards.org/snapshots/hikey/android/64
NOTE: I AM USING boot-fat.img,
and cache.img system.img userdata.img

Test result: I can see Android logo on my HDMI monitor. And I can use the serial console. However, the android desktop failed to show up, logcat stops at that:

D/libEGL ( 1511): Emulator without GPU support detected. Fallback to software renderer.
D/libEGL ( 1511): loaded /system/lib64/egl/libGLES_android.so
E/cutils-trace( 1511): Error opening trace file: Permission denied (13)
I/ArmToArm64Assembler( 1511): generated scanline__00000077:03010102_00000A01_00000000 23 ipp at [0x7fb55ea3c0:0x7fb55ea4cc] in 123333 ns
I/ArmToArm64Assembler( 1511): generated scanline__00000077:03545402_00000A01_00000000 60 ipp at [0x7fb55ea4e0:0x7fb55ea680] in 71667 ns
I/ArmToArm64Assembler( 1407): generated scanline__00000077:03010102_00000002_00000000 49 ipp at [0x7fb4f783c0:0x7fb4f78524] in 87500 ns
[   83.382008] healthd: battery none chg=

Here is the full log: https://pastebin.linaro.org/view/cc183bfc

**Comment by vishalbhoj** [comment]
This issue is due to the execve error from this bug:
https://github.com/96boards/bugs/issues/42

**Comment by docularxu** [comment]
Verified on snapshot build 65, https://builds.96boards.org/snapshots/hikey/android/65
Issue is fixed.

Close.
