### ISSUE TITLE
WiFi: cfg80211: [   18.977282] db.txt is empty, you should update it...

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#46]
[   18.976918] calling  cfg80211_init+0x0/0xf8 [cfg80211] @ 1055
[   18.977223] ------------[ cut here ]------------
[   18.977276] WARNING: CPU: 6 PID: 1055 at ../net/wireless/reg.c:511 regulatory_init+0x88/0x128 [cfg80211]()
[   18.977282] db.txt is empty, you should update it...
[   18.977287] Modules linked in:
[   18.977293]  cfg80211(+) rfkill wlcore_sdio mali st_drv
[   18.977310] CPU: 6 PID: 1055 Comm: systemd-udevd Tainted: G        W      3.18.0-linaro-hikey #1
[   18.977315] Call trace:
[   18.979854] [<ffffffc000088504>] dump_backtrace+0x0/0x124
[   18.979863] [<ffffffc000088638>] show_stack+0x10/0x1c
[   18.979872] [<ffffffc000808e1c>] dump_stack+0x74/0xb8
[   18.979880] [<ffffffc0000afdb4>] warn_slowpath_common+0x90/0xb8
[   18.979885] [<ffffffc0000afe28>] warn_slowpath_fmt+0x4c/0x58
[   18.979932] [<ffffffbffc0c317c>] regulatory_init+0x84/0x128 [cfg80211]
[   18.979972] [<ffffffbffc0c3070>] cfg80211_init+0x70/0xf8 [cfg80211]
[   18.979979] [<ffffffc000081548>] do_one_initcall+0x114/0x1a0
[   18.979988] [<ffffffc00011a990>] load_module+0x1664/0x1db0
[   18.979994] [<ffffffc00011b244>] SyS_finit_module+0x78/0x88
[   18.979998] ---[ end trace c1d1c4b9b702486d ]---
[   18.980042] cfg80211: Calling CRDA to update world regulatory domain

**Comment by koenkooi** [comment]
That's not really a bug: https://wireless.wiki.kernel.org/en/developers/regulatory

**Comment by docularxu** [comment]
Thanks Koen for the information. This issue is caused by enabling CONFIG_CFG80211_INTERNAL_REGDB=y in current defconfig. That's not what we should expect.

In next WiFi driver release (TI WL18xx R8.5), I will have this fixed. No CONFIG_CFG80211_INTERNAL_REGDB, CRDA and regulatory.bin will be the solution.

**Comment by docularxu** [comment]
This issue is fixed in the TI driver R8.5 release, which should be integrated into hikey build, as followed up in https://github.com/96boards/bugs/issues/65

**Comment by sbambrough** [comment]
Fixed.
