### ISSUE TITLE
HiKey - Debian X, regression issue in #258, X starts up much slower

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#47]
One regression issue was found between debian alip snapshot builds 254 and 258. https://builds.96boards.org/snapshots/hikey/debian

X windows in 258 doesn't come up immediately after system booted. Actually what i saw from hdmi monitor is: mouse icon comes first, then after ~30 seconds the descktop bar starts to appear.

After checking with Fathi, the rootfs in 254 and 258 are the same. Only difference is in kernel. So kernel commit id are:  #254-7fce8a4a
#258-cfffe011

So, these two patches are introducing this problem. They should be checked again: 
066db00 phy: phy-hisi: reset usb phy when board up
5c3773a mmc: dw_mmc: fix warning of clk_prepare_enable/clk_disable_unprepare

**Comment by docularxu** [comment]
Scott also reported that Debian booting up time in build 258 is longer than before. 

In the serial console log, it seems looping around this line for about 37 seconds:
A start job is running for Remount Root and Kernel F...

Not sure the above patches are introducing this problem at this moment. But we should check back on this.

**Comment by gaozhangfei** [comment]
https://github.com/96boards/linux/pull/37

**Comment by docularxu** [comment]
Verified on build 260. This issue is fixed.

Also what Scott reported "A start job is running for Remount Root and Kernel F..." takes too long, is also disappeared.

So, I close this issue.
