### ISSUE TITLE
HiKey: Default config missing many USB network adapters

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/bugs#48]
The HiKey docs say that users can use USB based network adapters when they want to avoid wireless. However many common USB network adapters are not enabled in HiKey kernel. Obvious examples include CONFIG_USB_PEGASUS, CONFIG_USB_RTL8150, CONFIG_USB_RTL8152 and CONFIG_USB_NET_DM9601 although I'm sure there are others.

It is hard to find comparisions by acording to http://elinux.org/RPi_USB_Ethernet_adapters it looks like we have worse coverage than RPi.

I'd expect the default config to be much more aggressive about enabling USB network adapters.

**Comment by fboudra** [comment]
https://github.com/96boards/linux/pull/40

**Comment by fboudra** [comment]
merged. https://github.com/96boards/linux/commit/7ac927dc0bd11a188e56ef8310a757006d00ccb2
