### ISSUE TITLE
fail to mount rootfs if flush it in uefi

### ISSUE THREAD

**Issue by hzhuang1** [96boards/bugs#49]
If flush rootfs by fastboot in UEFI, we'll fail to mount it later. If flush rootfs by fastboot bootloader, we could boot rootfs even after replacing fastboot bootloader by UEFI.

**Comment by gaozhangfei** [comment]
Two reasons:
1, uefi ArmPlatformPkg/ArmVExpressPkg/ArmVExpressFastBootDxe/ArmVExpressFastBoot.c does not consider offset
2. system.img is sparse file, rather than raw data, which can be mounted directly

**Comment by suihkulokki** [comment]
I now have a patch that implements sparse images in ArmVExpressFastBoot.c. The correct place to implement it is AndroidFastbootApp.c since the sparse code is platform independent. This however requires changing the ArmFastbootPlatformFlashPartition API, which requires discussion with upstream.

**Comment by fboudra** [comment]
https://github.com/96boards/edk2/pull/11

**Comment by hzhuang1** [comment]
Verified & applied.
