### ISSUE TITLE
Need enable PMIC hi6553's RTC driver

### ISSUE THREAD

**Issue by Leo-Yan** [96boards/bugs#51]
Currently in boot flow it will report RTC init failure, need enable hi6553's RTC driver to fix this issue.

**Comment by sbambrough** [comment]
If we don't have an RTC, why do we link in an RTC driver and have its initialization fail?

**Comment by gaozhangfei** [comment]
--- a/drivers/rtc/Kconfig
+++ b/drivers/rtc/Kconfig
@@ -19,7 +19,6 @@ if RTC_CLASS
 
 config RTC_HCTOSYS
        bool "Set system time from RTC on startup and resume"
-       default y

I don't think it is a issue, just a notification.
We can enable rtc later, keep this as a notification.

**Comment by sbambrough** [comment]
I understand it is harmless.  Question is why include it if there is no RTC
on the HiKey?

Scott

On Tue, Apr 28, 2015 at 10:38 PM, Zhangfei Gao <notifications@github.com>
wrote:

> --- a/drivers/rtc/Kconfig
> +++ b/drivers/rtc/Kconfig
> @@ -19,7 +19,6 @@ if RTC_CLASS
>
> config RTC_HCTOSYS
> bool "Set system time from RTC on startup and resume"
>
>    - default y
>
> I don't think it is a issue, just a notification.
> We can enable rtc later, keep this as a notification.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/51#issuecomment-97287037>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>

**Comment by gaozhangfei** [comment]
enable internal rtc
https://github.com/96boards/linux/pull/61

**Comment by gaozhangfei** [comment]
There are two rtc, one is on pmic, the other is internal.
The internal one is align with drivers/rtc/rtc-pl031.c
Also in power on region, power on only if power supplied, 
Supposed can be used in suspend/resume.

**Comment by ldts** [comment]
https://github.com/96boards/linux/pull/61

**Comment by ldts** [comment]
96boards/linux#61 reverted - this feature is not part of the milestone

**Comment by gaozhangfei** [comment]
Looks like the rtc patch is merged -> reverted, and never come back?

**Comment by ldts** [comment]
it is back on the hikey branch. it was never reverted from the base/hikey branch though.

**Comment by gaozhangfei** [comment]
Thanks, have verified base/hikey.
Then should this issue be closed?

**Comment by ldts** [comment]
yes
