### ISSUE TITLE
Debian: Unable to play audio using LXMusic

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#54]
Had to install xmms2 package; apt-get install xmms2
Had to run xmms2 config output.plugin pulse  -- seems to default to alsa
After these two commands I could play audio from the command line and the GUI.

**Comment by sbambrough** [comment]
LXMusic cannot find the command line client to add music to the playlist.

Solution:
apt-get install --no-install-recommends xmms2-client-cli

**Comment by sbambrough** [comment]
LXMusic cannot add .ogg files to the playlist.  There is no support for .ogg files in xmms2.

Solution:
apt-get install --no-install-recommends xmms2-plugin-vorbis

**Comment by sbambrough** [comment]
No audio played to the bluetooth speaker.  Problem is default output is alsa.

In .config/xmms2.conf have:
        <section name="output">
                <property name="buffersize">32768</property>
                <property name="flush_on_pause">1</property>
                <property name="plugin">alsa</property>
        </section>

Solution:
xmms2 server config output.plugin pulse

Then in .config/xmms2.conf will have:
        <section name="output">
                <property name="buffersize">32768</property>
                <property name="flush_on_pause">1</property>
                <property name="plugin">pulse</property>
        </section>

Is there any way to set this by default when the image is created?

**Comment by sbambrough** [comment]
This is still broken on snapshot 274.

To fix: 
sudo apt-get update
sudo apt-get install --no-install-recommends xmms2-client-cli xmms2-plugin-vorbis
xmms2 server config output.plugin pulse

xmms-client-cli installs the command line programs required by the LXMusic UI
the vorbis plugin is required to play .ogg files
the xmms2 command is needed to set the default audio output to use pulseaudio instead of alsa

once the plugins are installed and the output plugin configured the daemon needs to be reloaded
exit LXMusic
do a killall xmms2d

things will work after that.

**Comment by fboudra** [comment]
added packages and added fixed default output plugin:
https://git.linaro.org/ci/job/configs.git/commitdiff/1bb29e4cfd4d0b4f069568c0ab8b3b7d7fd1d711

**Comment by sbambrough** [comment]
+              cat << EOF | sudo tee -a rootfs/home/linaro/.profile
+            [ -f "$HOME/.config/xmms2/xmms2.conf" ] || xmms2 server config output.plugin pulse
+            EOF

This isn't working.  I see several problems:

1)  [ -f "$HOME/.config/xmms2/xmms2.conf" ] || xmms2 server config output.plugin pulse
The shell will short circuit the logical evaluation of the ||, and only ever execute the test for the config file.  This would need to be:
[ -f "$HOME/.config/xmms2/xmms2.conf" ] && xmms2 server config output.plugin pulse

2) .profile never seems to be executed
This is because we never open a login shell.  It does not seem to be executed if we boot straight to X, or when a LXTerminal window is opened.  It does get executed if I do ctrl+alt+F1 and login.  See: http://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell

3) This will reset the user's output to pulse, even if they change it.  Not likely in our case, but not user friendly.

This could work unless the config directory and conf file don't exist until xmms2 is run
sed -i 's/alsa/pulse' rootfs/home/linaro/.config/xmms2/xmms2.conf

Another solution would be to add this to .bashrc
[ -f "$HOME/.config/xmms2/xmms2.conf" ] && xmms2 server config output.plugin pulse
It is run for non-login shells and .profile loads it as well

If that doesn't work we could create a script to in ./config/xmms2/startup.d
Then that script will be run every time the server starts.

**Comment by fboudra** [comment]
1) the test is: if configuration *doesn't* exist, we create it and setup the default output plugin
we want to run it once and only once. it has been tested and it works as intended.
your line is bogus, if the file exists (which doesn't by default) then you run the configuration.

2) that's right, if you never open a login shell it isn't executed. It's a matter to apply the same logic and include the one-liner snippet to lxde session autostart.

3) no, see answer 1, the intent is to run the configuration once and set default to pulse.
after that, the user can change his default as he wants.

**Comment by fboudra** [comment]
problem 2 ack'ed and fixed. re-factored the logic to clarify the intent:
https://git.linaro.org/ci/job/configs.git/commitdiff/34434f8fd271dd9d78da6a278b357e8ddebf228d
