### ISSUE TITLE
HiKey - using fastboot + kernel, cannot reboot

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#55]
Hiikey, using fastboot and debian image, at the terminal command line, type in "reboot", the board cannot go reboot.

**Comment by docularxu** [comment]
SoC reset is implemented in PSCI. Patch submitted and merged, ref: https://github.com/96boards/arm-trusted-firmware/commit/7b62f222023a516772974461c050b79696a0ebe7

Considering fastboot will be obsoleted soon, I don't think we should put resources to solve this for fastboot. Meaning we don't want to patch the kernel to trigger SoC reset. PSCI is our solution to the community.

**Comment by docularxu** [comment]
Low priority, and leave it open for reference.

**Comment by docularxu** [comment]
Reviewed with Scott and Jorge. Since we are delivering fastboot to circuitco in production build, so this issue still need to be fixed asap.

When adding such code to kernel, need to think about conditioning between PSCI and no PSCI.

**Comment by Leo-Yan** [comment]
Pls apply PR: https://github.com/96boards/linux/pull/52

**Comment by ldts** [comment]
fixed:
