### ISSUE TITLE
Mali not installed on ALIP image

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#56]
I had to agree to a license before downloading the image, yet Mali is not installed on the image.

**Comment by fboudra** [comment]
ALIP has mali since build #263 (April 17th)

**Comment by sbambrough** [comment]
Using snapshop 267....

scottb@eagle:~$ ssh linaro@192.168.0.124
linaro@192.168.0.124's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Apr 21 02:47:29 2015 from eagle.bambrough.org
linaro@linaro-alip:~$ sudo su -
root@linaro-alip:~# find / -name libMali.so
root@linaro-alip:~# find / -name libmali.so
root@linaro-alip:~# find / -name libmali.so*
root@linaro-alip:~# 

Where are the MALI libs installed.  Used to be /usr/lib/aarch64-linux-gnu/mali-egl/

root@linaro-alip:~# ls /usr/lib/aarch64-linux-gnu/mali-egl
ls: cannot access /usr/lib/aarch64-linux-gnu/mali-egl: No such file or directory

**Comment by ldts** [comment]
also, having to agree to the license before the file can be downloaded is breaking my wget setup (part of my automated upgrade infrastructure)

is there a way to bypass this?

**Comment by sbambrough** [comment]
no, that's the whole point

On Tue, Apr 21, 2015 at 8:28 AM, Jorge A. Ramirez-Ortiz <
notifications@github.com> wrote:

> also, having to agree to the license before the file can be downloaded is
> breaking my wget setup (part of my automated upgrade infrastructure)
>
> is there a way to bypass this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/56#issuecomment-94775846>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>

**Comment by sbambrough** [comment]
Test snapshot 272.  Fixed.
