### ISSUE TITLE
Debian: blueman-applet will not launch

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#57]
It is trying to launch gconftool-2 and failing,

Solution:
apt-get install --no-install-recommends gconf2

blueman-applet failing to run also prevents blueman-manager from connecting to devices.

**Comment by sbambrough** [comment]
This is still broken on snapshot 274.  
The package gconf2 must be installed for the program gconftool-2 to be available.
The tool uses this program, the blueman-applet fails to load, and you cannot then connect to devices.
After installing, killall blueman-* processes running or reboot to have the UI work correctly.

**Comment by fboudra** [comment]
gconf2 package added.
