### ISSUE TITLE
Userdata partition not mounted, space not used or available

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#64]
Testing snapshot 272.  

The userdata partition should be mounted on but is not. Was expecting it mounted on /home.
```
linaro@linaro-alip:~$ mount 
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=110106,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=180156k,mode=755)
/dev/mmcblk0p9 on / type ext4 (rw,relatime,data=ordered)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/debug type cgroup (rw,nosuid,nodev,noexec,relatime,debug)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
tmpfs on /tmp type tmpfs (rw)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mmcblk0p6 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=90080k,mode=700,uid=1000,gid=1000)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=90080k,mode=700)
```

Looking at the filesystem
/dev/mmcblk0p9 - system partition
/dev/mmcblk0p10 - userdata
both have 1487856 1K blocks

Right now df reports 80% of the system partition is used.
```
linaro@linaro-alip:~$ df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/mmcblk0p9   1487856 1166572    304900  80% /
udev               10240       0     10240   0% /dev
tmpfs             180156    8836    171320   5% /run
tmpfs             450384       0    450384   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs             450384       0    450384   0% /sys/fs/cgroup
tmpfs             450384      16    450368   1% /tmp
/dev/mmcblk0p6     65390   15106     50284  24% /boot
tmpfs              90080       0     90080   0% /run/user/1000
tmpfs              90080       0     90080   0% /run/user/0
linaro@linaro-alip:~$ 
```

Right now du /usr reports:
```
linaro@linaro-alip:~$ sudo du /usr
867220	/usr
```
Thus /usr uses 58% of the root partition.
867220/1487856*100 = 58%

It seems to me we are in more danger of having failures installing additional software due to running out of space on / than we are in need of having a large home partition.  If might be better to copy /usr to a filesystem mounted on userdata, and leave /home on the system partition.

Then: 
We end up with 
userdata = /dev/mmcblk0p10 = 58% used
system = /dev/mmcblk0p9 = 20% used
(1166572-867220)/1487856*100 = 20%

Thus 80% of the system partition is available for /home.
This seems a better solution.

**Comment by suihkulokki** [comment]
Splitting root and /usr and / is a mess. We have to ask endusers to flash / and /usr images and make sure they are in sync.

Easiest solution is to make a ptable for debian that doesn't come with userdata partition, and only with a large system partition.

The best solution is using overlayfs - where system is read-only pristine linaro release, and userdata is mounted as overlay on top of it - any changes user does are installed to the overlay partion. the big advantage of the overlay approach is that user can anytime boot to the original rootfs by simply not mounting the overlay.

**Comment by sbambrough** [comment]
Con for the ptable approach is that we need two different partition tables for Linux and Android then.  But I take your point about splitting / and /usr.

Overlayfs sounds interesting.  Any suggestion on how you think it would work with system and userdata?

**Comment by gcgrey** [comment]
Current POR is to have two partition tables that are identical except for in Debian we have single partition spanning system & userdata and in Android we keep both. Testing is required to see if this will work - i.e. load partition table, boot and system for Debian and partition table, boot, system, cache and userdata for Android.

**Comment by fboudra** [comment]
new partition table for linux is published:
http://builds.96boards.org/snapshots/hikey/binaries/20150505/ptable-linux.img

It doesn't require recovery mode: sudo fastboot flash ptable ptable-linux.img
