### ISSUE TITLE
apt-get doesn't work out of the box

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#66]
You need to do an apt-get update first before any install succeeds.  Error messages are not clear that this needs to be done to resolve the issue.  Didn't use to happen.  Has something changed?  

Noticed this myself on snapshot 272.  George reported this on the weekend, and Jim Wilson has also reported this issue.  Might want to update the build to do an apt-get update before finishing.

**Comment by fboudra** [comment]
to reduce image size, we remove apt cache.

in any case, you should run apt-get update before any apt-get install command.
you don't know when the image has been built, the cache has changed and you'll have to run it anyway.
we shouldn't assume apt-cache is up-to-date. Hence shipping the cache isn't necessary.

**Comment by fboudra** [comment]
removing the milestone. we agreed to document the behavior.

**Comment by sbambrough** [comment]
Added back the milestone, assigned to George

**Comment by gcgrey** [comment]
Included in Getting Started notes
