### ISSUE TITLE
UEFI build 16, l-loader.bin is broken

### ISSUE THREAD

**Issue by davidrusling** [96boards/bugs#67]
Fails into a loop of exception reporting after I load l-loader.bin.   Build 15 works.  Here's the log from the serial port:
---
start enum.
Can not get device description command.
Switch to UART download...
�����������������������������������������������
Switch to aarch64 mode. CPU0 executes at 0xf9801000!
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.1(release):c543f68
NOTICE:  BL1: Built : 05:41:46, Apr 24 2015

Platform exception reporting:
ESR_EL3: 0000000002000000
ELR_EL3: 00000000f9802ed4
Platform exception reporting:
ESR_EL3: 0000000002000000
ELR_EL3: 00000000f9802ed4

**Comment by davidrusling** [comment]
Oh, and the boot manager returns "There is no supported device" for every command except setting a timeout...

**Comment by davidrusling** [comment]
Oh, and in the UEFI shell, the mappings do not look to have been set up:

Shell> map
Mapping table
     BLK0: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)
     BLK1: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(1,GPT,496847AB-56A1-4CD5-A1AD-47F4ACF055C9)
     BLK3: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(2,GPT,61A36FC1-8EFB-4899-84D8-B61642EFA723)
     BLK4: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(3,GPT,65007411-962D-4781-9B2C-51DD7DF22CC3)
     BLK5: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(4,GPT,496847AB-56A1-4CD5-A1AD-47F4ACF055C9)
     BLK6: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(5,GPT,00354BCD-BBCB-4CB3-B5AE-CDEFCB5DAC43)
     BLK7: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(6,GPT,5C0F213C-17E1-4149-88C8-8B50FB4EC70E)
     BLK8: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(7,GPT,BED8EBDC-298E-4A7A-B1F1-2500D98453B7)
     BLK9: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(8,GPT,A092C620-D178-4CA7-B540-C4E26BD6D2E2)
    BLK10: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(9,GPT,FC56E345-2E8E-49AE-B2F8-5B9D263FE377)
     BLK2: Alias(s):
          VenHw(B549F005-4BD4-4020-A0CB-06F42BDA68C3)/HD(10,GPT,064111F6-463B-4CE1-876B-13F3684CE16)
Shell>

**Comment by davidrusling** [comment]
Build 15 looks pretty functional...

**Comment by Leo-Yan** [comment]
This bug has been fixed by below commit, and has been merged. @hzhuang1 , @fboudra , could u check why have no new build images for this update

commit 5344c03283c25982c26343f1c795818a6cce5488
Author: Haojian Zhuang <haojian.zhuang@linaro.org>
Date:   Mon Apr 27 15:30:41 2015 +0800

    pll: add dsb after media pll clock init
    
    The dsb instruction must be added after media pll clock init.
    
    Otherwise, we'll get this error message.
    
    Platform exception reporting:
    ESR_EL3: 0000000002000000
    ELR_EL3: 00000000f9802ed0
    
    Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>

**Comment by fboudra** [comment]
https://github.com/96boards/arm-trusted-firmware/pull/32

**Comment by fboudra** [comment]
http://builds.96boards.org/snapshots/hikey/uefi/17

**Comment by davidrusling** [comment]
Thanks, I'll give it a spin when I have some time...
