### ISSUE TITLE
Enabling Wifi on boot breaks Bluetooth

### ISSUE THREAD

**Issue by fboudra** [96boards/bugs#7]
_From @usmanahmad-linaro on February 25, 2015 10:49_

 When configuring Wifi to start on boot uim/kim/bt doesn't work anymore.

_Copied from original issue: 96boards/linux#7_

**Comment by ldts** [comment]
I am starting wifi on rc.local at boot and uim/kim/bt initalizes properly when btwilink is blacklisted (otherwise btwilink it is started too early for uim to synch up).
is this still a bug?

**Comment by fboudra** [comment]
1. rc.local is irrelevant, it isn't the user expected way to start wifi (in addition, it is already too late in the boot process)
2. yes, it is still a reproducible bug: use build 119 and configure wlan0 as described in getting started

e.g. drop a wlan0 stanza in /etc/network/interfaces.d/

**Comment by ldts** [comment]
yes it is not the usual way to start wifi. however, what do you mean it being too late? If I understand correctly, Lollipop builds wait for the Android GUI to start before it configures the ethernet port. On first boot, this can take quite a long time - several minutes after the board appears to have booted.
how is using rc.local different to that situation.?
I'll try build 119.

**Comment by fboudra** [comment]
where do you see mentioned lollipop or android? build 119 is debian jessie. Vishal reports similar issue on android though, indicating that there's a problem on the wifi. So the question is not is there an issue related to wifi, we know there's an issue.

wrt rc.local, it is not relevant to the issue observed on debian jessie build because we will never use it in a debian build. That's great if it works for you with a rc.local hack but it isn't the problem that I try to fix here.

**Comment by ldts** [comment]
Mentioning android/lollipop's use case is a way to set an expectation with respect to time (not to ignore an issue). I simply don't know what too late means in your statement above. With that time reference in mind, I would have expected Android tests to behave just like rc.local. From what you say that is not the case - so this is good info.

**Comment by docularxu** [comment]
Today I verified two builds: Debian and Android.
1. Debian129 (http://builds.96boards.org/snapshots/hikey/debian/129). WiFi and bluetooth can work together. For WiFi, I tested it with ping to my router. For bluetooth I tested with 'hcitool scan'.

So, on Debian, this issue can be closed. Disagree?

2. Android25 (http://builds.96boards.org/snapshots/hikey/android/25). WiFi has the same 'sdio write failed (-110)' error as on debian. After disabled ELP mode, (running 'echo 0 > /sys/kernel/debug/ieee80211/phy0/wlcore/sleep_auth' upon booting in shell command line, or using the special wl18xx-conf.bin which sets sleep_auth to 0), the WiFi on Android can work stable.
For Bluetooth, I can go along the way to bluetooth 'On', list 'Available devices', and pairing with my mouth. However, the mouse pointer cannot be shown up on the screen. I'm not sure whether this is an android layer issue. I pinged Vishal for advice.

Today I verified two builds: Debian and Android.
1. Debian129 (http://builds.96boards.org/snapshots/hikey/debian/129). WiFi and bluetooth can work together. For WiFi, I tested it with ping to my router. For bluetooth I tested with 'hcitool scan'.

So, on Debian, this issue can be closed. Disagree?

2. Android25 (http://builds.96boards.org/snapshots/hikey/android/25). WiFi has the same 'sdio write failed (-110)' error as on debian. After disabled ELP mode, (running 'echo 0 > /sys/kernel/debug/ieee80211/phy0/wlcore/sleep_auth' upon booting in shell command line, or using the special wl18xx-conf.bin which sets sleep_auth to 0), the WiFi on Android can work stable.
For Bluetooth, I can go along the way to bluetooth 'On', list 'Available devices', and pairing with my mouth. However, the mouse pointer cannot be shown up on the screen. I'm not sure whether this is an android layer issue. I pinged Vishal for advice.

**Comment by vishalbhoj** [comment]
https://github.com/96boards/android_device_linaro_hikey/commit/421cd09604a3c349869b65ac41a5036c1e136c0a should fix the issue for Android. It updates the firmware with the version provided by Guodong.

**Comment by ldts** [comment]
@docularxu : yes Debian is fine.
can someone validate Android so we can close the issue?

**Comment by docularxu** [comment]
Vishal,

Any update?

-Guodong

**Comment by vishalbhoj** [comment]
BT works on Android build 47 when WiFi is turned on though WiFi itself has
authentication related issues.

**Comment by docularxu** [comment]
Vishal,

Thanks. And about "though WiFi itself has authentication related issues.",
you don't mean a WiFi driver/kernel issue, right? If not, please let me
know.

-Guodong

**Comment by docularxu** [comment]
I got your email. Sorry.
Now I am checking this "authentication issue".

-Guodong
