### ISSUE TITLE
Bluetooth manager won't pair keyboards

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#70]
Bluetooth manager won't pair keyboards that require more than 4 character passcode (i.e. most). 
Work-round is to use bluetoothctl:
$ sudo bluetoothctl -a
[bluetooth]# power on
[bluetooth]# agent KeyboardOnly
[bluetooth]# default-agent
[bluetooth]# pairable on
[bluetooth]# scan on
[bluetooth]# pair 01:02:03:04:05:06  (use your device - use tab to autocomplete)
[bluetooth]# trust 01:02:03:04:05:06
[bluetooth]# connect 01:02:03:04:05:06
[bluetooth]# quit

**Comment by sbambrough** [comment]
There is an alpha2 package from stretch that fixes the keyboard issue:
https://packages.debian.org/stretch/blueman

I downloaded the source, diff and .dsc files, built and installed the deb:
dpkg-source -x blueman_1.99~alpha2-1.dsc
cd blueman-1.99~alpha2
dpkg-checkbuilddeps 
installed build dependencies
dpkg-buildpackage -rfakeroot -uc -us -sa

Installed the .deb file I built
sudo apt-get purge blueman
sudo dpkg -i blueman_1.99~alpha2-1_arm64.deb
sudo apt-get install -f

Package I built can be found here:
wget http://people.linaro.org/~scottb/blueman_1.99~alpha2-1_arm64.deb

Tested on snapshot 276.

**Comment by fboudra** [comment]
Riku added latest blueman package to our overlay repository:
http://repo.linaro.org/ubuntu/linaro-overlay/pool/main/b/blueman/
