### ISSUE TITLE
Bluetooth LED does not light on Bluetooth activity

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#72]

**Comment by docularxu** [comment]
Command 'rfkill list bluetooth' can return the hci0 number. On hikey, it looks like:
# rfkill list bluetooth
1: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
, so getting number 1.

Then, rfkill1 is the trigger string for Bluetooth activity and can be used to trigger LED:
echo rfkill1 > /sys/class/leds/bt_active/trigger

**Comment by sbambrough** [comment]
This doesn't seem to work.  I do the above and the blue led comes on solid.  It doesn't blink with traffic at all.  It also doesn't seem to change when I power down the radio.  Basically seems to turn the led on.

**Comment by fboudra** [comment]
@sbambrough which build number is it?

**Comment by docularxu** [comment]
Scott told me it's build 285 ALIP. But in my test today, it works as expected: The LED can reflect the power on / off state. When you turn on/off Bluetooth through UI (Bluetooth icon in the right side of task bar), the LED will go on /off occordingly.

Note: 1) It's true that it doesn't blink upon bluetooth activity. It's not implemented for that.
2) It takes about 70 seconds for turning bluetooth on. The major cost is inside of download_firmware(). I am checking this and following up https://github.com/96boards/bugs/issues/78

**Comment by gcgrey** [comment]
> On May 5, 2015, at 10:13 AM, Guodong Xu <notifications@github.com> wrote:
> 
> Scott told me it's build 285 ALIP. But in my test today, it works as expected: The LED can reflect the power on / off state. When you turn on/off Bluetooth through UI (Bluetooth icon in the right side of task bar), the LED will go on /off occordingly.
> 
> Note: 1) It's true that it doesn't blink upon bluetooth activity. It's not implemented for that.
> 
I think it should be. The user expectation is that this is an “activity” LED - just like for WiFi.
George

**Comment by docularxu** [comment]
For WiFi, kernel module 'mac80211' implements a LED trigger to reflect wifi traffic. But for Bluetooth, there is no such trigger in kernel.

**Comment by docularxu** [comment]
Added LED trigger for bluetooth activity, both receive and transmit. By default, leds/bt_active will be bound to bluetooth transmit packets.

https://github.com/96boards/linux/pull/68

Tested with my bluetooth mouse and bluetooth sound box. Work fine.

**Comment by docularxu** [comment]
Updated https://github.com/96boards/linux/pull/69

**Comment by docularxu** [comment]
Fixed in snapshot build 294. Verified using bluetooth mouse and bluetooth sound box on ALIP image, and Pass.

Close this issue.
