### ISSUE TITLE
Yellow LED does not light on WLAN activity (regression in Snapshot 279)

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#73]
With updated WiFi software yellow LED no longer works (Snapshot 279)

**Comment by docularxu** [comment]
LED triggers need to be enabled for WiFi. That was not enabled by TI's driver release by default. Attached is a patch to fix that, and I have verified on my local platform.

Fathi,

Could you please apply that to: build-utilites/src/backports
, then regenerate the build?

Thanks.
Best regards,
Guodong Xu


Date: Sat, 2 May 2015 14:02:01 -0700

**Comment by fboudra** [comment]
Hi Guodong,

I already fixed the issue. I should have updated the bug....
https://git.linaro.org/ci/job/configs.git/commitdiff/e6431d2c9f00803af635965438eedacb527d9c48
