### ISSUE TITLE
Reboot takes several minutes

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#74]
In Build 279 reboot "often" seems to hang and then enter a state where the UI login window is shown before finally rebooting a few minutes later. 
Fathi notes:
The message that I observe when it happens is:
Starting Synchronise Hardware Clock to System Clock...
and then it's stuck here for a few minutes before it actually reboot.

**Comment by Leo-Yan** [comment]
Reproduced this issue w/t below log, same w/t Fathi's log. will check for more detailed info:

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent                                                                                                                                 
permitted by applicable law.                                                                                                                                                                      
root@linaro-alip:~# reboot                                                                                                                                                                        
         Starting Synchronise Hardware Clock to S[  207.419763] (stc): 2 not un-registered(stc): 3 not un-registered                                                                              
[[  207.425661] (stc): 4 not un-registered  OK  ] Stopped target Graphical Interface.                                                                                                             
         Stopping Light Display Manager...                                                                                                                                                        
[  OK  ] Stopped target Multi-User System.                                                                                                                                                        
         Stopping Initialize hardware monitoring sensors...                                                                                                                                       
[  OK  ] Stopped Initialize hardware monitoring sensors.

**Comment by Leo-Yan** [comment]
Fixed by PR: https://github.com/96boards/linux/pull/63

**Comment by docularxu** [comment]
Verified on build no. 285. Both developer and ALIP images.

Close.
