### ISSUE TITLE
dmesg filled with Bluetooth messages

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#75]
Using Build 279 I successfully paired with a Bluetooth speaker and played music tracks. 
However, dmesg shows floods of hci0: type 1 len xx messages
These are continuous if Bluetooth is enabled. 
If this is debugging data it needs to be removed.

**Comment by sbambrough** [comment]
Looks like CONFIG_DEBUG_INFO is enabled.  If this is unset, then default log mesage level is changed from 7 to 4.  Suggest we turn off debug info in the kernel and test.

If this doesn't work, I suggest editing /etc/sysctl.conf or /etc/sysctl.d/99-sysctl.conf.
Uncomment the line:
```
#kernel.printk = 3 4 1 3
```

**Comment by Leo-Yan** [comment]
Fixed by : https://github.com/96boards/linux/pull/64

**Comment by sbambrough** [comment]
fixed.
