### ISSUE TITLE
Spurious symlinks in /lib/modules/3.18.0-linaro-hikey/

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#76]
linaro@linaro-alip:~$ ls -al /lib/modules/3.18.0-linaro-hikey/
total 204
drwxrwxr-x 4 linaro linaro  4096 May  4 14:31 .
drwxr-xr-x 3 root   root    4096 May  4 14:37 ..
lrwxrwxrwx 1 linaro linaro    70 May  4 14:29 build -> /home/buildslave/workspace/96boards-hikey/builddir-3.18.0-linaro-hikey
drwxrwxr-x 5 linaro linaro  4096 May  4 14:29 kernel
-rw-r--r-- 1 linaro linaro 44478 May  4 14:31 modules.alias
-rw-r--r-- 1 linaro linaro 44160 May  4 14:31 modules.alias.bin
-rw-rw-r-- 1 linaro linaro 12215 May  4 14:29 modules.builtin
-rw-r--r-- 1 linaro linaro 15104 May  4 14:31 modules.builtin.bin
-rw-r--r-- 1 linaro linaro  3492 May  4 14:31 modules.dep
-rw-r--r-- 1 linaro linaro  6254 May  4 14:31 modules.dep.bin
-rw-r--r-- 1 linaro linaro    52 May  4 14:31 modules.devname
-rw-rw-r-- 1 linaro linaro  2033 May  4 14:29 modules.order
-rw-r--r-- 1 linaro linaro    55 May  4 14:31 modules.softdep
-rw-r--r-- 1 linaro linaro 16992 May  4 14:31 modules.symbols
-rw-r--r-- 1 linaro linaro 20561 May  4 14:31 modules.symbols.bin
lrwxrwxrwx 1 linaro linaro    41 May  4 14:29 source -> /home/buildslave/workspace/96boards-hikey
drwxrwxr-x 5 linaro linaro  4096 May  4 14:31 updates
linaro@linaro-alip:~$

**Comment by fboudra** [comment]
fix commited: https://git.linaro.org/ci/job/configs.git/commitdiff/d0248fe575c20cd600e599d71272ed70207f1c3b
