### ISSUE TITLE
UEFI boot manager changes don't persist

### ISSUE THREAD

**Issue by suihkulokki** [96boards/bugs#8]
Selecting the boot manager[3]: from the below UEFI menu:

The default boot selection will start in   9 seconds
[1] Linux from eMMC
[2] Shell
[3] Boot Manager

Allows updating and creating new entries. However, no changes persist over reboot. Edits to the "Linux from eMMC" dont stay, and any new entries created are gone after the next boot.

**Comment by hzhuang1** [comment]
Yes, it's an issue since NVM isn't supported yet. It will be fixed later.

**Comment by suihkulokki** [comment]
Right now I can work without nvm, I have a startup.nsh that lets me boot the way I want. So this is not high priority for me. Things like psci and cpufreq support and more urgent.

**Comment by hzhuang1** [comment]
Now setting environment variable is implemented. I'll send the patch to the mailing list.

**Comment by hzhuang1** [comment]
It should be fixed now. Please verify it with latest uefi code base.

**Comment by suihkulokki** [comment]
Verified as closed, thanks
