### ISSUE TITLE
xmms2 not installed on Debian developer snapshot 287

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#82]
After logging in as linaro, get the following error:

/home/linaro/bin/xmms2-output-plugin-pulse: 3: /home/linaro/bin/xmms2-output-plugin-pulse: xmms2: not found

```
root@linaro-developer:~# dpkg -l | grep xmms
ii  xmms2-core                         0.8+dfsg-12                       arm64        XMMS2 - core package
ii  xmms2-plugin-id3v2                 0.8+dfsg-12                       arm64        XMMS2 - ID3v2 plug-in
ii  xmms2-plugin-mad                   0.8+dfsg-12                       arm64        XMMS2 - libmad based mp3 decoder
ii  xmms2-plugin-pulse                 0.8+dfsg-12                       arm64        XMMS2 - PulseAudio output plug-in
```

Solution:
apt-get install --no-install-recommends xmms2-client-cli xmms2-plugin-vorbis

Similar to problems in https://github.com/96boards/bugs/issues/54

**Comment by sbambrough** [comment]
Tried both emmc and sdcard images.  Both have same problem.

**Comment by fboudra** [comment]
fixed.
