### ISSUE TITLE
booting from SD card, error with High-capacity cards

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#83]
Zhangfei and I tested the sd card image: https://builds.96boards.org/snapshots/hikey/debian/289/hikey-jessie_alip_20150506-289.img.gz

Snapshot build 289.

Using dd to write it to microSD card. Result is:
1. SDHC class4, 8GB. It can boot into X.

But,
2. Sandisk, SDHC class 10, 16GB
3. Kingston, SDHC UHS-1, 32GB, http://item.jd.com/430479.html
On these two cards, the image cannot boot on Hikey. And when we plug back these cards to Ubuntu PC, the rootfs partitions cannot be mounted either. This make me think it isn't hikey kernel issue.

**Comment by fboudra** [comment]
Zhangfei has retryed with the command that I suggested:
sudo dd if=hikey-jessie_alip_20150506-289.img of=/dev/mmcblk0 bs=4M oflag=sync status=noxfer

It can boot, on both 4G card and 32G uhs cards.

**Comment by docularxu** [comment]
with this command, my 16GB sandisk microsd can boot also.
This command should be added into 'Getting start guide'.

Close.
