### ISSUE TITLE
WIFI failure when turn on and off at the second time

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#84]
root@linaro-alip:~# ifconfig -a
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1009 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1009 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:81760 (79.8 KiB)  TX bytes:81760 (79.8 KiB)

wlan0     Link encap:Ethernet  HWaddr 84:dd:20:6e:e8:c6  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1130 (1.1 KiB)  TX bytes:1550 (1.5 KiB)

root@linaro-alip:~# ifconfig wlan0 down

root@linaro-alip:~# ifconfig -a
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1009 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1009 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:81760 (79.8 KiB)  TX bytes:81760 (79.8 KiB)

wlan0     Link encap:Ethernet  HWaddr 84:dd:20:6e:e8:c6  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1130 (1.1 KiB)  TX bytes:1550 (1.5 KiB)

root@linaro-alip:~# ifconfig wlan0 up
[  326.974419] wlcore: ERROR timeout waiting for the hardware to complete initialization
[  480.666817] INFO: task kworker/2:2:1022 blocked for more than 120 seconds.
[  480.673762]       Tainted: G           O   3.18.0-linaro-hikey #1
[  480.679902] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.687824] Call trace:
[  480.690368] INFO: task sd-resolve:1152 blocked for more than 120 seconds.
[  480.697202]       Tainted: G           O   3.18.0-linaro-hikey #1
[  480.703299] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.

Message from [  480.711186] Call trace:
syslogd@linaro-al[  480.715190] INFO: task ifconfig:1609 blocked for more than 120 seconds.
ip at May  7 01:[  480.723194]       Tainted: G           O   3.18.0-linaro-hikey #1
36:58 ...
 ker[  480.730667] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
nel:[  480.687824[  480.739881] Call trace:
] Call trace:

Message from syslogd@linaro-alip at May  7 01:36:58 ...
 kernel:[  480.711186] Call trace:

**Comment by sbambrough** [comment]
Trying to connect to Hitron CGN3ROG router/cable modem.

WIFI supports
802.11 g/b/n mixed on 2.4.GHz band SSID: Saskatoon
802.11 a/n mixed on 5 GHz band  SSID: Saskatoon-5G

Attempting to connect via the 2.4 GHz band using SSID Saskatoon, security is WPA/WPA2-AES

I switched from a successful connection to another AP.  Changed wlan0 config file, and rebooted.

**Comment by sbambrough** [comment]
scottb@eagle:~$ iwlist wlan0 scan
wlan0     Scan completed :
          Cell 01 - Address: 58:6D:8F:F3:43:E5
                    Channel:36
                    Frequency:5.18 GHz (Channel 36)
                    Quality=25/70  Signal level=-85 dBm  
                    Encryption key:on
                    ESSID:"Vancouver"
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=000003f7b80b175b
                    Extra: Last beacon: 36544ms ago
                    IE: Unknown: 000956616E636F75766572
                    IE: Unknown: 01088C129824B048606C
                    IE: Unknown: 030124
                    IE: Unknown: 0406000200000000
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: 2D1AFE0117FFFFFF0000000000000000000000000000000000000000
                    IE: Unknown: 3D1624050600000000000000000000000000000000000000
                    IE: Unknown: DD1E00904C33FE0117FFFFFF0000000000000000000000000000000000000000
                    IE: Unknown: DD1A00904C3424050600000000000000000000000000000000000000
                    IE: Unknown: DD06005043030000
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (1) : TKIP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD180050F2020101800003A4000027A4000042435E0062322F00
                    IE: Unknown: DD770050F204104A0001101044000102103B000103104700106F50885592EC376DD75E1372FC32918B102100074C696E6B73797310230003574150102400033132331042000531323334351054000800060050F20400011011000956616E636F7576657210080002200C103C0001021049000600372A000120

**Comment by sbambrough** [comment]
Password is wrong.  Fixed it, tried ifconfig wlan0 down, ifconfig wlan0 up -- seems to hang
Rebooted and wlan0 comes up correctly.

Behaviour on bad password doesn't seem recoverable without a reboot.  You should investigate.

**Comment by sbambrough** [comment]
Connect to 5GHz SSID which is not supported, get similar non-recoverable issues.  Cannot fix /etc/network/interfaces.d/wlan0 to point to another SSID, and do ifconfig wlan0 down, ifconfig wlan0 up and have a successful connection.  Have to reboot.

**Comment by docularxu** [comment]
Fixed in https://github.com/96boards/linux/pull/77

**Comment by docularxu** [comment]
Fixed in Debian 305. Close.
