### ISSUE TITLE
Unable to flash l-loader and ptable

### ISSUE THREAD

**Issue by suihkulokki** [96boards/bugs#86]
According to comment on UEFI wikipage[1]:

PS l-loader.bin, ptable.img should be flashed in recovery mode, since these are not on real partition

Code to support these non-real partitions needs to be added to UEFI fastboot code so recovery mode won't be necessary for UEFI updates. 

[1] https://github.com/96boards/documentation/wiki/UEFI

**Comment by fboudra** [comment]
ptable can be flashed without recovery mode.

**Comment by hzhuang1** [comment]
ptable and l-loader could be only flushed in recovery mode since these two spaces are not real partitions.

**Comment by hzhuang1** [comment]
In ATF recovery mode, I hacked the code to handle ptable & l-loader. But AndroidFastBoot.efi is a common application in UEFI, we shouldn't add any hard coding in it. The only way to flush ptable & l-loader is in ATF recovery mode.

**Comment by suihkulokki** [comment]
AndroidFastBoot.efi is a common application, yes. But it calls  mPlatform->FlashPartition ( PartitionName, ... which is implemented ArmVExpressFastBoot.c, where it only checks partititions against gpt table. I think ArmVExpressFastBoot.c Needs to be copied to ArmHiKeyFastBoot.c where FlashPartition is implemented to support the pseudo partitions,

**Comment by hzhuang1** [comment]
Good point. It seems that we could handle the ptable & l-loader.

**Comment by hzhuang1** [comment]
https://github.com/96boards/edk2/pull/20

We could flash ptable into eMMC by UEFI. But we can't flash l-loader since l-loader exists in boot area of eMMC. We only simultate user data area of eMMC as harddisk, not boot area. If we want to support flashing boot area, we need to append some extension on diskio in UEFI.

Is it enough to this feature?

**Comment by suihkulokki** [comment]
The ptable pull request looks good to me. I think we still need to support updating the boot area. Else users will end up with l-loader and fip.bin from different builds, unless they fiddle the jumper and upload l-loader with burn-boot every time they.

**Comment by suihkulokki** [comment]
I've been tolk it is not possible to upload l-loader with the old bootloader, so it's not a regression. Feel free to close the bug with the merge request.

**Comment by fboudra** [comment]
afaict, it matches fastboot bootloader feature so it looks good to me. flashing ptable is enough.

**Comment by hzhuang1** [comment]
The pull request is merged. Close the bug now.
