### ISSUE TITLE
Bluetooth Manager occasionally fails to open

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#87]
After a paring session or after opening/closing the bluetooth manager a few times, it occasionally stops to launch. After killing the 'blueman-manager' process or rebooting the board, we can launch bluetooth manager again. Probably blueman is occasionally crashing.

**Comment by docularxu** [comment]
I tested on Debian 303, cannot reproduce. Try pairing with a bluetooth mouth and then turning on/off bluetooth manager about 10 times, no error.

Would you please check again?

**Comment by usmanahmad-linaro** [comment]
Cannot reproduce the issue on Debian 305. Bluetooth manager opens up every time.
