### ISSUE TITLE
TI WIFI out of tree driver not working in Snapshots build 94

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#88]
Need to make sure the new TI WIFI out of tree driver is integrated with the Android build and working successfully.

**Comment by vishalbhoj** [comment]
There is a kernel crash with out of tree kernel module when built with android related configs. Here is the panic:
https://pastebin.linaro.org/view/5353ac0e

Goudong was able to reproduce the same issue with android kernel on a debian filesystem. Goudong is currently looking at the issue.

**Comment by docularxu** [comment]
After screening each of the Android specific configs, finally narrowed down the problemic code change is in here. TI for some reason adds these code section in net/wireless/core.c. Need to investigate why. I will involve TI FAE in the investigation process.

As a quick fix, like below, Vishal verified that WIFI modules now can work smoothly on Android.

== 

 /build-utilites/src/driver$ git diff net/wireless/core.c
diff --git a/net/wireless/core.c b/net/wireless/core.c
index 9d160d4..f9b3b0d 100644
--- a/net/wireless/core.c
+++ b/net/wireless/core.c
@@ -563,6 +563,7 @@ int wiphy_register(struct wiphy *wiphy)
                                rdev->wiphy.wowlan->pattern_max_len)))
                return -EINVAL;
 
+#if 0
 #ifdef CONFIG_ANDROID
        /* use wowlan by default */
        if (rdev->wiphy.wowlan->flags & WIPHY_WOWLAN_ANY) {
@@ -577,6 +578,7 @@ int wiphy_register(struct wiphy *wiphy)
        }
 #endif
 #endif
+#endif

**Comment by vishalbhoj** [comment]
Prebuilt Wifi modules have been added to the build. Wifi works on http://builds.96boards.org/snapshots/hikey/aosp/104
