### ISSUE TITLE
Bluetooth mouse and keyboard support

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#90]
The AOSP build shall support Bluetooth mice and keyboards.

**Comment by docularxu** [comment]
Verified with BT mouse in local build. Works smoothly.

Note: one issue is: there is still no 'Bluetooth' menu in 'Settings' app. I have to touch and hold 'Settings shortcut' in WIDGETS in order to find bluetooth setting.

**Comment by vishalbhoj** [comment]
I see BT in settings. Did you use the latest snapshots build ?

**Comment by docularxu** [comment]
Which version is this fixed? I am using #99.

Date: Mon, 18 May 2015 23:43:55 -0700

**Comment by fboudra** [comment]
there's a build 100: http://builds.96boards.org/snapshots/hikey/aosp/100

**Comment by vishalbhoj** [comment]
I see BT in settins on 100 and it should be the case with buill 99 as well. Nothing has changed wrt BT recently.  

https://github.com/96boards/linux/pull/72  should get BT mouse working.

**Comment by vishalbhoj** [comment]
BT mouse works with http://builds.96boards.org/snapshots/hikey/aosp/102
