### ISSUE TITLE
USB speed switch utility

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#91]
Need to install usb_speed switch utility -- on GitHub and support the utility in AOSP build.

**Comment by docularxu** [comment]
Kernel layer support and debugfs interfaces have been developed and verified by Zhangfei. Need to integrate with Android user apps. Assigning to Scott.

**Comment by vishalbhoj** [comment]
USB speed Switch app has been written and integrated in the  build. Please test it on http://builds.96boards.org/snapshots/hikey/aosp/107?dl=/snapshots/hikey/aosp/107/

**Comment by vishalbhoj** [comment]
The sources for the app is here: https://github.com/96boards/android_packages_apps_UsbSpeedSwitch

**Comment by docularxu** [comment]
Works for me on Android 101. Verified.
