### ISSUE TITLE
Live wallpapers do not run

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#95]
1. Live wallpapers don't run
2. No wallpapers or gallery images

**Comment by vishalbhoj** [comment]
The live wallpapers that are part of AOSP 5.1 release have issues when built with dex preopt enabled. There are few fixes related to the same in AOSP master branch for the wallpapers. Will build and test the master branch for wallpapers and update the same in build if they work.

**Comment by vishalbhoj** [comment]
Holo and Bubbles live wallpaper work on http://builds.96boards.org/snapshots/hikey/aosp/105?dl=/snapshots/hikey/aosp/105/
