### ISSUE TITLE
/dev/ttyUSB0 not created when you connect a USB serial device (e.g. a bricked HiKey)

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#99]
Running "udevadm monitor" on an ubuntu box shows module/usb_wwan and module/option are loaded before the ttyUSB0 port appears. 
On HiKey this does not happen and the ttyUSB port does not appear.
Please fix so I can use my HiKey as my "linux computer" to upload builds to my 96Boards instead of my Ubuntu box.

**Comment by sbambrough** [comment]
Jorge, can you investigate adding the required modules to the config please.

**Comment by ldts** [comment]
sure

**Comment by ldts** [comment]
can you find your product/vendor in the ftdi_sio list of supported devices?

just do:

$ modinfo ftdi_sio | grep v{product}p{version}

for instance I can see my device (vendor 0x0403, product 0x6001) 
[root@96 ]$ modinfo ftdi_sio | grep 0403p6001
alias:          usb:v0403p6001d*dc*dsc*dp*ic*isc*ip*in*

and subsequently dmesg shows the following when the device is inserted:

[  620.877745] ftdi_sio 1-1.2:1.0: FTDI USB Serial Device converter detected
[  620.877960] usb 1-1.2: Detected FT232RL
[  620.880162] usb 1-1.2: FTDI USB Serial Device converter now attached to ttyUSB0

**Comment by ldts** [comment]
this commit adds support for some common devices:
https://github.com/96boards/linux/commit/dab7c0450de919194169917547faa12ed8bbf0af

it should be enough.

**Comment by gcgrey** [comment]
no ….

dmesg says this:

[27406.392396] usb 1-1.1: new full-speed USB device number 6 using dwc2

modinfo ftdi_sio | greo 12d1:3609
returns nothing

lsusb
returns 
Bus 001 Device 007: ID 12d1:3609 Huawei Technologies Co., Ltd. 

BTW this is a direct connect between the “host” HiKey USB Type A port (using the Hikey like a Linux PC) and the microUSB port on a slave HiKey with LK3-4 made (ie in recovery mode) - ie no FTDI device involved. 

This works on my Ubuntu PC - the /dev/ttyUSB0 port appears and I can use hisi-idt.py - it does not work using the HiKey as a host. 

OK …. then if I change strategy and use an FTDI cable between the host Type A USB and the Expansion port UART - note NOT the debug serial UART then I DO get the ttyUSB0 device to appear. (Then of course the hisi-idt.py operation fails because its not the debug UART). 

The bug is that this does not work on the direct USB connection - ie Type A USB to HiKey microUSB port. 

George

**Comment by ldts** [comment]
give me a minute. I forgot to add CONFIG_USB_SERIAL_OPTION !

**Comment by gcgrey** [comment]
Going to bed - I’ll try tomorrow … do I just pick up the new snapshot to try it?
George

**Comment by ldts** [comment]
I just pushed 
I am not sure if jenkins will recompile having send one commit right after the other (not sure how the trigger will behave)

**Comment by ldts** [comment]
yes I misunderstood: what it was required was the usb gsm modem driver (as identified by the events you mentioned in the first line of the requirement). this should be there now.

**Comment by gcgrey** [comment]
No difference in Snapshot 299 - did this make it in?

**Comment by ldts** [comment]
no it didnt
https://builds.96boards.org/snapshots/hikey/debian/299

the config is missing.

**Comment by fboudra** [comment]
build #300 (contains the config) failed to publish because the build took too much time. another build has been triggered.

**Comment by gcgrey** [comment]
Tested and demonstrated fixed in Snapshot 301. 
Good job - closing bug.
